<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit962d1a7851a8eec06d8b65490470baf5
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\EventDispatcher\\' => 34,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
    );

    public static $prefixesPsr0 = array (
        'f' => 
        array (
            'fXmlRpc' => 
            array (
                0 => __DIR__ . '/..' . '/lstrojny/fxmlrpc/src',
            ),
        ),
        'I' => 
        array (
            'Infusionsoft' => 
            array (
                0 => __DIR__ . '/..' . '/infusionsoft/php-sdk/src',
                1 => __DIR__ . '/..' . '/infusionsoft/php-sdk/tests',
            ),
        ),
        'G' => 
        array (
            'Guzzle\\Tests' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/tests',
            ),
            'Guzzle' => 
            array (
                0 => __DIR__ . '/..' . '/guzzle/guzzle/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit962d1a7851a8eec06d8b65490470baf5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit962d1a7851a8eec06d8b65490470baf5::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit962d1a7851a8eec06d8b65490470baf5::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
